name = "KitCxx"
uuid = "03f1e65e-3944-4d3d-abc7-708cdb1f19f6"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Xtensor = "65419b8a-9a19-58ae-bde3-3f7e1d1bf8ef"

[compat]
CxxWrap = "0.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
test = ["Test", "BenchmarkTools"]
